name: CI

on:
  pull_request:
  check_run:
    types:
      - created
      - rerequested
  check_suite:
    types:
      - requested
      - rerequested

jobs:
  ci:
    runs-on: macOS-10.14
    steps:
      - name: brew pull
        run: |
          brew update-reset "$(brew --repository)"

          HOMEBREW_INSTALL_BUNDLER_GEMS_FIRST=1 brew config

          brew tap "${GITHUB_REPOSITORY}"

          # Get latest version of `brew cask ci` command.
          if [ "${GITHUB_REPOSITORY}" != Homebrew/homebrew-cask ]; then
            brew update-reset "$(brew --repository homebrew/cask)"
          fi

          brew update-reset "$(brew --repository "${GITHUB_REPOSITORY}")"

          brew pull --clean "${PR_URL}"
        env:
          PR_URL: ${{ github.event.pull_request._links.html.href || github.event.check_run.check_suite.pull_requests[0].url }}
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
      - name: brew cask ci
        run: |
          cd "$(brew --repository "${GITHUB_REPOSITORY}")"
          export HOMEBREW_GITHUB_EVENT_NAME="${GITHUB_EVENT_NAME}"
          export HOMEBREW_GITHUB_EVENT_PATH="${GITHUB_EVENT_PATH}"
          export HOMEBREW_CASK_ANNOTATION_APP_KEY="${{ secrets.HOMEBREW_CASK_ANNOTATION_APP_KEY }}"
          export HOMEBREW_GITHUB_API_TOKEN="${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}"
          brew cask ci
        env:
          CI: true
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
